[package]
name = "nodalync-econ"
version = "0.7.1"
edition.workspace = true

[dependencies]
nodalync-types = { workspace = true }
nodalync-crypto = { workspace = true }
thiserror = "1.0"
sha2 = "0.10"

[dev-dependencies]
serde_json = "1.0"
